// examples/vite-demo/src/card.vue
<template>
  <div :class="cls">
    <slot />
  </div>
</template>

<script>
import { computed, defineComponent } from 'vue'
import * as stylex from '@stylexjs/stylex'

const styles = stylex.create({
  card: {
    border: '1px solid red',
    color: 'red'
  }
})

export default defineComponent({
  setup() {
    const cls = computed(() => stylex.props(styles.card).className)
    return { cls }
  }
})
</script>

// examples/remix-demo/app/Card.tsx
import * as stylex from '@stylexjs/stylex'
import { tokens } from './theme.stylex'

const styles = stylex.create({
  root: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 16,
    boxShadow: '0 0 16px rgba(0, 0, 0, 0.1)',
    color: tokens.primaryTextColor
  }
})

export default function Card({ children }: { children: React.ReactNode }) {
  return <div {...stylex.props(styles.root)}>{children}</div>
}
